# Generated by Django 5.2.1 on 2025-06-29 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('produto', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('quantidade', models.FloatField()),
                ('custo', models.FloatField()),
                ('valor_unitario_bruto', models.FloatField()),
                ('desconto', models.FloatField()),
                ('acrescimo', models.FloatField()),
                ('valor_unitario_liquido', models.FloatField()),
                ('valor_total_liquido', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'venda_itens',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('Não identificado', 'Nao Identificado'), ('Ativa', 'Ativa')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_bruto', models.FloatField(blank=True, null=True)),
                ('acrescimo', models.FloatField(blank=True, null=True)),
                ('desconto', models.FloatField(blank=True, null=True)),
                ('credito_troca', models.FloatField(blank=True, null=True)),
                ('valor_liquido', models.FloatField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionario', to='funcionario.funcionario')),
                ('produtos', models.ManyToManyField(related_name='vendas', through='venda.ItemVenda', to='produto.produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'venda_vendas',
            },
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.venda'),
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('parcelas', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='venda.venda')),
            ],
            options={
                'db_table': 'venda_pagamentos',
            },
        ),
    ]
