# Generated by Django 5.2.1 on 2025-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_venda_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='imposto_aliquota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
