# Generated by Django 5.2.1 on 2025-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_itemvenda_imposto_aliquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='imposto_aliquota',
            field=models.FloatField(default=0),
        ),
    ]
