# Generated by Django 5.2.1 on 2025-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_alter_itemvenda_imposto_aliquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Não identificado', 'Nao Identificado'), ('Ativa', 'Ativa'), ('Cancelada', 'Cancelada')], max_length=20),
        ),
    ]
