# Generated by Django 5.2.1 on 2025-11-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_alter_formapagamento_id_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_atualizacao_origem',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
