# Generated by Django 5.2.1 on 2025-11-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_venda_data_atualizacao_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='cor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
