# Generated by Django 5.2.1 on 2025-12-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_id_origem'),
        ('venda', '0008_alter_itemvenda_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionario_item', to='funcionario.funcionario'),
        ),
    ]
