# Generated by Django 5.2.1 on 2025-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_itemvenda_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='trocado',
            field=models.BooleanField(default=False),
        ),
    ]
