# Generated by Django 5.2.1 on 2025-06-29 13:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaIntegrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenant_sistemas',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_api', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_api', models.CharField(blank=True, max_length=50, null=True)),
                ('token_api', models.CharField(blank=True, max_length=70, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('sistema_integrado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tenants', to='tenant.sistemaintegrado')),
            ],
            options={
                'db_table': 'tenant_tenants',
            },
        ),
    ]
