# Generated by Django 5.2.1 on 2025-09-21 14:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_adiciona_dados_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lojas', to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_lojas',
            },
        ),
    ]
