# Generated by Django 5.2.1 on 2025-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='imposto_aliquota_padrao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
