# Generated by Django 5.2.1 on 2025-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenant_imposto_aliquota_padrao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='imposto_aliquota_padrao',
        ),
        migrations.AddField(
            model_name='loja',
            name='imposto_aliquota_padrao',
            field=models.FloatField(default=0),
        ),
    ]
