# Generated by Django 5.2.1 on 2025-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_remove_tenant_imposto_aliquota_padrao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='documento_api',
            new_name='api_document',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='token_api',
            new_name='api_token',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='codigo_api',
            new_name='api_user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_host',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
