# Generated by Django 5.2.1 on 2025-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_adiciona_power_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='id_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
