# Generated by Django 5.2.1 on 2025-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_adiciona_informezz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
