# Generated by Django 5.2.1 on 2026-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_tenant_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bi_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bi_api_key_active',
            field=models.BooleanField(default=False),
        ),
    ]
