# Generated by Django 5.2.1 on 2025-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_alter_fornecedor_id_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
