# Generated by Django 5.2.1 on 2025-09-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('tenant', '0003_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.loja'),
        ),
    ]
