# Generated by Django 5.2.1 on 2025-10-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_estoque_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='reservado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='gtin',
        ),
        migrations.AddField(
            model_name='estoque',
            name='cor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
