# Generated by Django 5.2.1 on 2025-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_estoque_reservado_remove_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_atualizacao_origem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_atualizacao_origem',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
