# Generated by Django 5.2.1 on 2025-11-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_estoque_data_atualizacao_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
