# Generated by Django 5.2.1 on 2025-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_estoque_cor_alter_produto_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='colecao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_colecao_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
