# Generated by Django 5.2.1 on 2025-06-29 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('tenant', '0001_initial'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Não identificado', 'Nao Identificado'), ('Entradas', 'Entradas'), ('Saídas', 'Saidas')], max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoriafinanceira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'financeiro_categorias',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'financeiro_instituicoes',
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('conta', models.CharField(blank=True, max_length=255, null=True)),
                ('digito_verificador', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('instituicao_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeiro.instituicaofinanceira')),
            ],
            options={
                'db_table': 'financeiro_contas',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('data_competencia', models.DateTimeField(blank=True, null=True)),
                ('data_lancamento', models.DateTimeField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Não identificado', 'Nao Identificado'), ('Crédito', 'Credito'), ('Débito', 'Debito')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoriafinanceira')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.contafinanceira')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedor.fornecedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'db_table': 'financeiro_lancamentos',
            },
        ),
    ]
