# Generated by Django 5.2.1 on 2025-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicaofinanceira',
            name='id_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
    ]
