# Generated by Django 5.2.1 on 2025-06-29 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_origem', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj_loja', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'funcionario_funcionarios',
            },
        ),
    ]
