# Generated by Django 5.2.1 on 2025-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_remove_funcionario_cnpj_loja_funcionario_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id_origem',
            field=models.CharField(max_length=50),
        ),
    ]
