GET http://127.0.0.1:8000/v1/integrador/maestriabi/estoques/ HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NjUzNzM1LCJpYXQiOjE3NTk2MTc3MzUsImp0aSI6IjBjMTIyNDY4MDUzYTRiMTk5Zjc1MjYxOTY5ZDM1ODQ5IiwidXNlcl9pZCI6ImQwZjY1M2E3LWFjZDEtNGU5ZC05ZGVmLWM0MzM1ZDdlODg3MSJ9.6pc9I2d2xPB37QLDKZehODqBBwr1bsmCkLqTiDGomLY

###

GET http://127.0.0.1:8000/v1/integrador/maestriabi/produtos/ HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NjUzNzM1LCJpYXQiOjE3NTk2MTc3MzUsImp0aSI6IjBjMTIyNDY4MDUzYTRiMTk5Zjc1MjYxOTY5ZDM1ODQ5IiwidXNlcl9pZCI6ImQwZjY1M2E3LWFjZDEtNGU5ZC05ZGVmLWM0MzM1ZDdlODg3MSJ9.6pc9I2d2xPB37QLDKZehODqBBwr1bsmCkLqTiDGomLY

###

GET http://127.0.0.1:8000/v1/integrador/maestriabi/vendas/ HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NjUzNzM1LCJpYXQiOjE3NTk2MTc3MzUsImp0aSI6IjBjMTIyNDY4MDUzYTRiMTk5Zjc1MjYxOTY5ZDM1ODQ5IiwidXNlcl9pZCI6ImQwZjY1M2E3LWFjZDEtNGU5ZC05ZGVmLWM0MzM1ZDdlODg3MSJ9.6pc9I2d2xPB37QLDKZehODqBBwr1bsmCkLqTiDGomLY
