GET http://127.0.0.1:8000/v1/integrador/maestriabi/estoques/ HTTP/1.1
X-POWERBI-KEY: X9_0y72GoLUbemeisJmea1z6_0YLXI_rBduGUXsftg91wqkzQ5WcVA

###

GET http://127.0.0.1:8000/v1/integrador/maestriabi/produtos/ HTTP/1.1
X-POWERBI-KEY: X9_0y72GoLUbemeisJmea1z6_0YLXI_rBduGUXsftg91wqkzQ5WcVA

###

GET http://127.0.0.1:8000/v1/integrador/maestriabi/vendas/ HTTP/1.1
X-POWERBI-KEY: X9_0y72GoLUbemeisJmea1z6_0YLXI_rBduGUXsftg91wqkzQ5WcVA