# Generated by Django 5.2.1 on 2025-10-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EstoqueBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=255)),
                ('mes', models.CharField(max_length=3)),
                ('ano', models.IntegerField()),
                ('codigo', models.CharField(max_length=255)),
                ('imposto', models.DecimalField(decimal_places=6, max_digits=6)),
                ('estoque_custo_unit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('estoque_pecas', models.DecimalField(decimal_places=6, max_digits=18)),
                ('custo_total', models.DecimalField(decimal_places=6, max_digits=18)),
                ('estoque_vlr', models.DecimalField(decimal_places=6, max_digits=18)),
                ('data', models.DateField()),
                ('tenant_id', models.UUIDField()),
            ],
            options={
                'db_table': 'vw_maestriabi_estoques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=255)),
                ('desc_produto', models.TextField(max_length=255)),
                ('categoria', models.CharField(max_length=255, null=True)),
                ('fornecedor', models.CharField(max_length=255, null=True)),
                ('nivel_1', models.CharField(max_length=255, null=True)),
                ('nivel_2', models.CharField(max_length=255, null=True)),
                ('nivel_3', models.CharField(max_length=255, null=True)),
                ('tenant_id', models.UUIDField()),
            ],
            options={
                'db_table': 'vw_maestriabi_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendaBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=255)),
                ('mes', models.CharField(max_length=3)),
                ('ano', models.IntegerField()),
                ('codigo', models.CharField(max_length=255)),
                ('custo_total', models.DecimalField(decimal_places=6, max_digits=18)),
                ('venda_qnt', models.DecimalField(decimal_places=6, max_digits=18)),
                ('venda_vlr', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descontos', models.DecimalField(decimal_places=6, max_digits=18)),
                ('venda', models.CharField(max_length=255)),
                ('vendas', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lucro_bruto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('data', models.DateField()),
                ('tenant_id', models.UUIDField()),
            ],
            options={
                'db_table': 'vw_maestriabi_vendas',
                'managed': False,
            },
        ),
    ]
